# Generated by Django 4.1.7 on 2023-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_human_competition_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='cnp',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
