# Generated by Django 4.1.7 on 2023-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_brand_alter_car_color_alter_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
