# Generated by Django 4.1.7 on 2023-03-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanCompete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_in', models.PositiveIntegerField(null=True)),
                ('sponsor', models.CharField(max_length=100, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.competition')),
            ],
        ),
    ]
