# Generated by Django 4.1.7 on 2023-03-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cancompete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='participating_car',
        ),
    ]
